### ISSUE TITLE
Lazy defaultValue?

### ISSUE THREAD

**Issue by gzak** [launchdarkly/dotnet-server-sdk#13] opened 2016-07-12 01:06 UTC
Would probably be useful to support lazy default values, i.e. a signature like this:

```
bool Toggle(string key, User user, Func<bool> defaultValueProvider);
```

In some cases the fallback might not be static, but might be difficult to compute (in our case we're falling back to our old toggle system, which involves a DB lookup.

**Comment by jkodumal** [comment] 2016-07-12 18:19
Great idea-- definitely valuable and not something easy to work around in client code. @drichelson , what do you think?

**Comment by drichelson** [comment] 2016-07-13 16:42
This seems like a great idea. Thanks @gzak for the suggestion!

**Comment by gzak** [comment] 2016-11-18 03:09
Then again, there are downsides to encouraging default values, particularly for binary toggles: if you disable the toggle, but forget to also disable it in your fallback system, you'll inadvertently end up enabling it gobally (at least, that was the case with the V1 dashboard). We definitely made that mistake once...

**Comment by eli-darkly** [comment] 2018-06-12 21:38
Sorry this one fell through the cracks, but I've re-put it onto the list of features we intend to add.

**Comment by gzak** [comment] 2018-06-12 21:56
Related idea to consider, particularly for .NET: maybe an async version (this would also require async versions of all the toggle methods themselves).

**Comment by aleric323** [comment] 2020-05-28 15:55
+1 for async support

**Comment by eli-darkly** [comment] 2020-05-28 19:38
Async variation methods are a different issue, so please feel free to file a new issue for that.

I'm going to close this current issue, because (as we should have realized earlier) lazy default values are unlikely to be implemented in the foreseeable future. The problem is that they're not compatible with one of the basic guarantees of the analytics event system. Here's why:

The analytics data for every flag evaluation includes the default value that was specified in the application code. This is surfaced on the LD dashboard so you can see what value would be used in the case of a service interruption. Therefore, if the default value is computed lazily... that computation will still need to be done no matter what, for every evaluation, which would make it in effect not lazy at all.

**Closed by eli-darkly** 2020-05-28 19:38 UTC
Labels: enhancement
